FROM node:latest

LABEL maintainer="haroldbarros@gmail.com"

ENV MONGO_DB_CONNECTION_VAR ""
ENV FIXED_ACCESS_TOKEN_VAR ""

RUN git clone https://github.com/haroldjose30/Omnibus.git

RUN cd Omnibus/backend
WORKDIR /Omnibus/backend

RUN yarn install

EXPOSE 3333

CMD cp ./src/secrets_example.js ./src/secrets_real.js && \
    cat ./src/secrets_real.js && \
    yarn start
  #sed -i 's/MONGO_DB_CONNECTION_VAR/$MONGO_DB_CONNECTION_VAR/g' ./src/secrets_real.js && \
    #sed -i 's/FIXED_ACCESS_TOKEN_VAR/$FIXED_ACCESS_TOKEN_VAR/g' ./src/secrets_real.js && \
 
 
#To Build a docker image
#docker build -t haroldbarros/omnibus:v1.0 .

#To Run a docker image
#docker run --env=MONGO_DB_CONNECTION_VAR=mongo_db_example  --env=FIXED_ACCESS_TOKEN_VAR=token_example -p3333:3333 haroldbarros/omnibus:v1.0

#Then push with the following
#docker login
#docker push haroldbarros/omnibus:v1.0