FROM node:latest

LABEL maintainer="haroldbarros@gmail.com"

ENV MONGO_DB_CONNECTION_VAR ""
ENV FIXED_ACCESS_TOKEN_VAR ""

RUN git clone https://github.com/haroldjose30/Omnibus.git

RUN cd Omnibus/backend
WORKDIR /Omnibus/backend

RUN yarn install

EXPOSE 3333

CMD cp ./src/secrets_example.js ./src/secrets_real.js && \
    yarn start
 
#To Build a docker image
#docker build -t haroldbarros/omnibus:v1.0 .

#To Run a docker image
#docker run --env=MONGO_DB_CONNECTION_VAR=mongo_db_example  --env=FIXED_ACCESS_TOKEN_VAR=token_example -p3333:3333 haroldbarros/omnibus:v1.0
#docker run --env="MONGO_DB_CONNECTION_VAR=mongodb+srv://OmnibusUser:EMByCJVn1hsw9tYp@haroldjose30-ftano.gcp.mongodb.net/OmnibusDb?retryWrites=true&w=majority"  --env="FIXED_ACCESS_TOKEN_VAR=5ed00d17-e3e1-4632-b339-e697c35bcf70" -p3333:3333 haroldbarros/omnibus:v1.0


#Then push with the following
#docker login
#docker push haroldbarros/omnibus:v1.0